version = 0.1

[default.global.parameters]
region = "ap-southeast-1"

[default.build.parameters]
template_file = "infra/template.yaml"

[default.deploy.parameters]
stack_name = "cloffice-backend"
resolve_s3 = true
s3_prefix = "cloffice-backend"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ProjectName=\"cloffice\" AlertEmail=\"phuocloc782004@gmail.com\" CorsAllowOrigin=\"http://localhost:5173\" EnableCloudFront=\"false\" CloudFrontWebAclArn=\"\" EnablePointInTimeRecovery=\"false\""
image_repositories = []
confirm_changeset = true

[default.delete.parameters]
stack_name = "cloffice-backend"
region = "ap-southeast-1"
